pull_request_rules:
  - name: automatic merge when reviewed
    conditions:
      - "#approved-reviews-by=BanterBoy"
      - status-success=Imgbot - Pull Request
    actions:
      merge:
        method: merge

pull_request_rules:
  - name: automatic merge for ImgBot pull requests
    conditions:
      - author=imgbot[bot]
      - status-success=Travis CI - Pull Request
    actions:
      merge:
        method: merge

pull_request_rules:
  - name: delete head branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch: {}