pull_request_rules:
  - name: automatic merge when passes and  review
    conditions:
      - "#approved-reviews-by>=1"
      - author=BanterBoy
      - base=master
    actions:
      merge:
        method: merge
