pull_request_rules:
  - name: automatic merge when reviewed
    conditions:
      - "#approved-reviews-by=BanterBoy"
      - status-success=Imgbot - Pull Request
    actions:
      merge:
        method: merge
